
#define BP_ERROR_STATEMENT           "unexpected statement"
#define BP_ERROR_SYMBOL              "unexpected symbol"
#define BP_ERROR_VARIABLE_GET        "variable access out of bound"
#define BP_ERROR_VARIABLE_SET        "variable update out of bound"
#define BP_ERROR_VARIABLE_MAX        "too many variables"
#define BP_ERROR_VARIABLE_NAME       "variable name too long"
#define BP_ERROR_FUNCTION_CALL       "function call max depth exceeded"
#define BP_ERROR_FUNCTION_DEFINITION "undefined function"
#define BP_ERROR_FUNCTION_END        "function end not found"
#define BP_ERROR_FUNCTION_NAME       "function name too long"
#define BP_ERROR_FUNCTION_MAX        "too many functions"
#define BP_ERROR_PARAMETERS          "too many parameters"
#define BP_ERROR_RETURN              "non matching return"
#define BP_ERROR_CYCLE_MAX           "cycle max depth exceeded"
#define BP_ERROR_CYCLE_NEXT          "non matching next"
#define BP_ERROR_WHILE_MAX           "while max depth exceeded"
#define BP_ERROR_STRING_MAX          "too many strings"
#define BP_ERROR_STRING_END          "string end not found"
#define BP_ERROR_STRING_GET          "string access out of bound"
#define BP_ERROR_SQUARE_PARENTHESIS  "non matching square parenthesis"
#define BP_ERROR_BLOCK               "non matching condition delimiter"
#define BP_ERROR_ROUND_PARENTHESIS   "non matching round parenthesis"
#define BP_ERROR_MEM_SET             "memory update out of bound"
