
#define BP_ERROR_STATEMENT           "unexpected statement"
#define BP_ERROR_SYMBOL              "unexpected symbol"
#define BP_ERROR_VARIABLE_GET        "variable read failure"
#define BP_ERROR_VARIABLE_SET        "variable write failure"
#define BP_ERROR_VARIABLE_MAX        "too many variables"
#define BP_ERROR_VARIABLE_NAME       "variable name too long"
#define BP_ERROR_FUNCTION_CALL       "too many nested calls"
#define BP_ERROR_FUNCTION_DEFINITION "undefined function"
#define BP_ERROR_FUNCTION_END        "function end not found"
#define BP_ERROR_FUNCTION_MAX        "too many functions"
#define BP_ERROR_FUNCTION_NAME       "function name too long"
#define BP_ERROR_FUNCTION_PARAMS     "too many parameters"
#define BP_ERROR_RETURN              "non matching return"
#define BP_ERROR_FOR_MAX             "too many nested for"
#define BP_ERROR_NEXT                "non matching next"
#define BP_ERROR_WHILE_MAX           "too many nested while"
#define BP_ERROR_FILE_OPEN           "file open failure"
#define BP_ERROR_FILE_MAX            "file write failure"
#define BP_ERROR_STRING_MAX          "too many strings"
#define BP_ERROR_STRING_END          "string end not found"
#define BP_ERROR_STRING_GET          "string read failure"
#define BP_ERROR_SINGLE_QUOTE        "non matching ''"
#define BP_ERROR_ROUND_PARENTHESIS   "non matching ()"
#define BP_ERROR_SQUARE_PARENTHESIS  "non matching []"
#define BP_ERROR_BLOCK               "non matching if else end"
#define BP_ERROR_MEM_SET             "memory write failure"
#define BP_ERROR_DIV_ZERO            "division by zero"
#define BP_ERROR_RESULT_SET          "result write failure"
#define BP_ERROR_RESULT_GET          "result read failure"
